### ISSUE TITLE
can't install via NPM

### ISSUE THREAD

**Issue by vance** [cobookman/express-sql-session#2]
Node v4

4 warnings and 9 errors generated.

make: **\* [Release/obj.target/node_sqlite3/src/database.o] Error 1

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)

gyp ERR! stack     at emitTwo (events.js:87:13)

gyp ERR! stack     at ChildProcess.emit (events.js:172:7)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp ERR! System Darwin 14.5.0

gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64"

gyp ERR! cwd /Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3

gyp ERR! node -v v4.0.0

gyp ERR! node-gyp -v v3.0.1

gyp ERR! not ok 

node-pre-gyp ERR! build error 

node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)

node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)

node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

node-pre-gyp ERR! System Darwin 14.5.0

node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd /Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3

node-pre-gyp ERR! node -v v4.0.0

node-pre-gyp ERR! node-pre-gyp -v v0.6.9

node-pre-gyp ERR! not ok 

Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/Nick/emixer/eMixer/node_modules/express-sql-session/node_modules/sqlite3/lib/binding/node-v46-darwin-x64' (1)

npm ERR! Darwin 14.5.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v4.0.0

npm ERR! npm  v2.14.2

npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.

npm ERR! This is most likely a problem with the sqlite3 package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node-pre-gyp install --fallback-to-build

npm ERR! You can get their info via:

npm ERR!     npm owner ls sqlite3

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/Nick/emixer/eMixer/npm-debug.log

**Comment by cobookman** [comment]
Just updated my nodejs version to v4.1.0 on OS X 10.10.5 and reinstalled the package without any problems.

Based on your log it seems like sqlite3 isn't installing.  What OS are you running.
